version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/sheets_to_web_user/sheets_to_web/staticfiles
    expose:
      - 8000
    env_file:
      - ./app/.env.prod
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    command: redis-server
    expose:
      - 6379
    restart: unless-stopped
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: celery -A sheets_to_web worker --loglevel=debug
    env_file:
      - ./app/.env.prod
    depends_on:
      - db
      - redis
  celery-beat:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: celery -A sheets_to_web beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./app/.env.prod
    depends_on:
      - web
      - db
      - redis
  telegram:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: python telegram_start.py
    env_file:
      - ./app/.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./app/.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/sheets_to_web_user/sheets_to_web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume: