version: '3.8'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/sheets_to_web
    ports:
      - 8000:8000
    env_file:
      - ./app/.env.dev
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    command: redis-server
    expose:
      - 6379
    restart: unless-stopped
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile-celery
    command: celery -A sheets_to_web worker --loglevel=debug
    env_file:
      - ./app/.env.dev
    volumes:
      - ./app:/usr/src/sheets_to_web
    depends_on:
      - db
      - redis
  celery-beat:
    build:
      context: ./app
      dockerfile: Dockerfile-celery
    command: celery -A sheets_to_web beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./app/.env.dev
    volumes:
      - ./app:/usr/src/sheets_to_web
    depends_on:
      - db
      - redis
  telegram:
    build:
      context: ./app
      dockerfile: Dockerfile-celery
    command: python telegram_start.py
    env_file:
      - ./app/.env.dev
    volumes:
      - ./app:/usr/src/sheets_to_web
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sheets_to_web

volumes:
  postgres_data: